server:
  port: 8081
spring:
  webflux:
    base-path: /applicant-service
  application:
    name: apppostulante
  data:
    mongodb:
      uri: mongodb://gitecsl:giyecsl2025@134.122.125.240:27017/admin
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springdoc: DEBUG